[Unit]
Wants=network-online.target
After=network-online.target

[Service]
ExecStartPre=
ExecStartPre=/usr/local/sbin/prime-wait-address 172.16.253.231 120
ExecStartPre=/usr/sbin/nginx -t -q -g 'daemon on; master_process on;'
